version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - backend_uploads:/app/data/uploads
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_uploads: